### ISSUE TITLE
Help a noob?

### ISSUE THREAD

**Issue by marroen** [PyvesB/eclipse-solargraph#14]
I installed Solargraph on the Eclipse Marketplace but I can not find Ruby on my Other Perspectives. Consequentally I can neither make a new Ruby project (I think, I can not find Ruby on the Wizard page when creating a new project).

**Comment by marroen** [comment]
Edit: I made a generic project and added a 'File' (not Ruby file) and called it main.rb and I could then install the gem. I think it works fine now but perhaps you know if there's something more I should do!

**Comment by PyvesB** [comment]
Hello @martyro ! 👋🏻 

There is no Ruby perspective or project type. As you've noticed, the plugin simply kicks in when you interact with a Ruby file, no matter which project it's part of and no matter which perspective is opened.

Maybe this could be clarified by adding a sentence or two somewhere in the README?

**Comment by marroen** [comment]
Yeah I agree, it would be helpful to know the introductory steps after install, especially for newbies.
When it says "you're good to go!" after install, then the next intuitive steps is to make a Ruby project to test out, but it would be nice to specify exactly how to do this, especially after just using Eclipse for Java projects in the past.

**Comment by marroen** [comment]
By the way, thanks for such a neat plugin that allows me to use my favorite IDE for my favorite new language! Much love!

**Comment by PyvesB** [comment]
> 
> 
> Yeah I agree, it would be helpful to know the introductory steps after install, especially for newbies.

I've added a note about this in the [installation section](https://github.com/PyvesB/eclipse-solargraph#cd-plugin-installation). If need-be, a new "usage" section can be added in the future, but for now hopefully it's good enough.

> 
> 
> By the way, thanks for such a neat plugin that allows me to use my favorite IDE for my favorite new language! Much love!

Thanks, much appreciated! Feel free to leave a star on the repository. 😉

**Comment by marroen** [comment]
Thank you and yes I did. Closing.
