### ISSUE TITLE
Help with customising behaviour.

### ISSUE THREAD

**Issue by myshkin-uk** [PyvesB/eclipse-solargraph#15]
If there is a better place to ask, please send me there.

I have installed solargraph with my eclipse IDE SOLELY TO GET A SYNTAX-HIGHLIGHT EDITOR FOR RUBY. I used to have one but it evaporated on an eclipse upgrade.

I have no clue what a language server is, or what else solargraph could do for me, and I probably don't care.

I have some simple issues

I HATE the colours in the syntax highlighting ( comments are such a light colour as to be unreadable on my monitor ) and haven't a clue how to alter them.
The string-auto-complete after I type "don't" in a comment is driving me mad

For Java I can just drill down to

a syntax-colours page and set them.
an behaviour page and turn off auto-suggest.

Can't see anything like that for solargraph in the eclipse drop-down pages..

So where do I start please?

**Comment by PyvesB** [comment]
Hello @myshkin-uk ! 👋🏻 

> I have no clue what a language server is, or what else solargraph could do for me, and I probably don't care.

Basically the language server gives you additional features such as code completion, documentation hovers, rename refactoring, find references, jump to declarations, code outline, and a few others. If you don't want those features and only care about simple syntax highlighting, you can disable the language server by going to _Preferences_ -> _Language Servers_ and untick the three entries pertaining to Solargraph.

> I HATE the colours in the syntax highlighting ( comments are such a light colour as to be unreadable on my monitor ) and haven't a clue how to alter them.

You can right-click in a Ruby editor and use the _Switch to Theme..._ option. Additional themes can de added in _Preferences_ -> _TextMate_ -> _Theme_.

> The string-auto-complete after I type "don't" in a comment is driving me mad

This is a known limitation of the tm4e project, I previously reported an issue about this here: https://github.com/eclipse/tm4e/issues/227

However, I believe you can disable the auto-complete for apostrophes completely by oing to _Preferences_ -> _TextMate_ -> _Language Configurations_.

Hopefully this helps clarify things a little. 😉

**Comment by myshkin-uk** [comment]
Thanks - at least it gives me a start :-)
I did wonder about themes - but other editors seem to have their own independent settings. Ah well...

David

**Comment by myshkin-uk** [comment]
Yup - switching theme looks great - thanks.
I was stuck on 'solarised ..." which makes comments a very light grey.
