### ISSUE TITLE
Can I do a tour-of-the-building test on what solargraph is offering me?

### ISSUE THREAD

**Issue by myshkin-uk** [PyvesB/eclipse-solargraph#16]
PY,

I didn't mean I wanted nothing to do with language-servers - just that I didn't know if I DID have any use for them.

I'm not sure if I have solargraph up-and-doing.

I obviously have a syntax-highlighted editor - but I have no knowledge of whether the rest of the features are in operation.

Is there a quick set of steps I can run through to see if it is working, and what sorts of things it is doing for me?

TVM.

David

**Comment by PyvesB** [comment]
Hello David! 👋🏻 

One simple thing you can try is what is shown in one of the README's screenshots:
https://raw.githubusercontent.com/PyvesB/eclipse-solargraph/master/images/editor.png

If you've got autocompletion with the Ruby documentation when pressing Ctrl + Space, it means Solargraph is working. The [list of features in the README](https://github.com/PyvesB/eclipse-solargraph#gem-features-at-a-glance) will give you more things to try out, but it is not exhaustive. This project, (eclipse-solargraph) is basically a thin layer between [lsp4e](https://projects.eclipse.org/projects/technology.lsp4e) and [solargraph](https://github.com/castwide/solargraph), in other words when one or the other get updated, new features appear in Eclipse without me having to do anything. 😄
