### ISSUE TITLE
Create Eclipse launch configuration

### ISSUE THREAD

**Issue by akurtakov** [PyvesB/eclipse-solargraph#2]
This is needed so one can pass parameters to the launcher.
Example code would be:
for arg in ARGV
   puts arg
end
and passing it some parameters like "one two"

**Comment by PyvesB** [comment]
Hey @akurtakov ! This would indeed be a nice addition to the plugin. You mentioned in a mail that you would take a look at contributing this, is it still a plan?

**Comment by akurtakov** [comment]
I hope to be able to look at it still but opened this one for the sake of the record.
