### ISSUE TITLE
[improvement] syntax checking / diagnostics enabled by default

### ISSUE THREAD

**Issue by pldavid2** [PyvesB/eclipse-solargraph#20]
Excerpt from @PyvesB comment here https://github.com/PyvesB/eclipse-solargraph/issues/19#issuecomment-1038188992

Solargraph gem code shows diagnostics are disabled by default: https://github.com/castwide/solargraph/blob/2ea80efdb5f02744b74f5af98c67174a55ab7c41/lib/solargraph/language_server/host.rb#L632

It seems that these should be enabled without users having to worry about turning them on explicitly. Adding a config override in the plugin seems like a good idea, if someone really wants to disable them, they can always create a [Solargraph configuration file](https://solargraph.org/guides/configuration) in their workspace and specify `reporters: []`.

**Comment by PyvesB** [comment]
Thanks for opening a dedicated issue for this @pldavid2!

Would you like to contribute the fix by any chance? According to my experimentations from earlier, I believe that the only thing that's required is to override the `getInitializationOptions` method in the `SolargraphStreamConnectionProvider` class, and simply return a map containing a key `"diagnostics"` with a value of `true`. No worries if you're not up for that. 😉

**Comment by pldavid2** [comment]
Oh my knowledge of solar and eclipse plugins is very limited :worried: 
If you don't mind i prefer to wait you have some time to check it, but don't hurry at all :wink:

**Comment by PyvesB** [comment]
Done! Will release as part of version 1.0.0 with some other improvements. :)

**Comment by pldavid2** [comment]
Great work, thank you! This is a great addition! :clap: :clap: :clap:

PS: For the record, I notice that sometimes diagnostics seems to hang. I mean I make a change in the code and diagnostics on the file are not updated anymore, although I set cache false on rubocop file.
But I don't think it's a problem with the plugin but from solargraph, as checking the eclipse log I'm not seeing any log line there or exception thrown.

**Comment by PyvesB** [comment]
> But I don't think it's a problem with the plugin but from solargraph

You're probably right on this one. If you've got a precise set of steps to reproduce, feel free to share, I can take a closer look.
