### ISSUE TITLE
Support debugging

### ISSUE THREAD

**Issue by akurtakov** [PyvesB/eclipse-solargraph#3]
There is Ruby debug adapter protocol implementation now https://github.com/castwide/readapt and lsp4e supports one too so it should be possible to add support now.

**Comment by PyvesB** [comment]
Hey @akurtakov! Yes, I'm aware of Readapt and actually started implementing support a few weeks back. It didn't quite work then but I believe I was almost there: debugging Ruby code through Eclipse was functional, however, for some reason I had to start Readapt through the command line for things to work properly. This was back in August in the very early days of Readapt, so I decided to stash the changes locally and focus on other work in the meantime, but I'm hoping to pick this up again soon. 😉

**Comment by PyvesB** [comment]
I'm still having the same issues with the latest version of Readapt. I've pushed my work in progress to a branch (https://github.com/PyvesB/eclipse-solargraph/tree/debug) and [sent a mail to the LSP4E list](https://www.eclipse.org/lists/lsp4e-dev/msg00456.html).

**Comment by PyvesB** [comment]
Okay, so I think this is simply due to the fact that Readapt does currently not support communication over stdin/stdout. I've opened the following issue: https://github.com/castwide/readapt/issues/3

**Comment by PyvesB** [comment]
Progress:
![readapt](https://user-images.githubusercontent.com/10694593/67892942-9907f580-fb4d-11e9-8091-614d42a55058.gif)

It works, but the user experience is not great. Either the linked Readapt issue or [Bug 552451](https://bugs.eclipse.org/bugs/show_bug.cgi?id=552451) would have to be solved to make this more viable.

**Comment by PyvesB** [comment]
Okay, so I've implemented debugging support in the above commit! 🎉 

I'm not planning on releasing this just yet: it currently requires to manually build and install Readapt from the master branch. There also are a few outstanding issues I'm discussing with the author. Once a new release of Readapt is published to rubygems.org, this plugin will automatically install it and wire things up into Eclipse with the code I've pushed.

There will probably be things to refine and improve at a later point. But for now, I would say initial debugging support is implemented, so I'll close this issue. 😉

**Comment by akurtakov** [comment]
Is there progres on release with debug support?

**Comment by PyvesB** [comment]
> Is there progres on release with debug support?

All the code is ready on my side. There were a few issues with the Readapt implementation which I helped investigate and test in recent weeks (see https://github.com/castwide/readapt/issues/3). The last remaining bit is now a new release of the Readapt gem, which is planned before the end of the month, but that's outside my control. 😉
