### ISSUE TITLE
Unsigned content approval

### ISSUE THREAD

**Issue by wieczorek1990** [PyvesB/eclipse-solargraph#30]
When installing in a fresh Eclipse CDT some unsigned content was to be approved.

**Comment by PyvesB** [comment]
Hello @wieczorek1990 👋🏻 

Yes, the project's setup is pretty simple, the produced artifacts are not signed :)

**Comment by wieczorek1990** [comment]
If you do not plan to sign them, please close the issue.

W dniu sob., 17.02.2024 o 14:58 Pierre-Yves Bigourdan <
***@***.***> napisał(a):
