### ISSUE TITLE
Freezes while editing Ruby

### ISSUE THREAD

**Issue by mrj** [PyvesB/eclipse-solargraph#32]
Hello,

While editing Ruby I'm getting frequent (multiple times a minute) freezes for several seconds. Any typing during these freezes is shown at the current cursor position, but things like positioning the cursor with a click, selecting text, and scrolling don't proceed until the freeze finishes.

It feels like the Ruby parser is working hard especially when the Ruby is incomplete and has errors.

Solargraph 0.5, Eclipse 2024-03 (4.31.0) (Build id 20240307-1437).

**UPDATE**:  Much improved after restarting Eclipse. Eclipse rapidly takes Java memory usage to over 1GB, but the problem doesn't manifest until later. I don't know why Solargraph is the only component of Eclipse that regularly freezes its UI after extensive usage. Garbage collection?

**Comment by PyvesB** [comment]
Hello @mrj! 👋🏻 

Sorry to hear this hasn't been the smoothest of experiences! Could you please upgrade to the latest version of the plugin, version 0.5 dates back from 2020, there's been quite a few improvements since then. 😉

**Comment by mrj** [comment]
Seems to be a one-off. Apologies.
