### ISSUE TITLE
Can't open js.erb files

### ISSUE THREAD

**Issue by mrj** [PyvesB/eclipse-solargraph#33]
I get the following error when I try to open a file with a ".js.erb" suffix:

![Solargraph Create js erb ](https://github.com/PyvesB/eclipse-solargraph/assets/111995/d49683d1-164e-429f-b5d7-bd628b34b102)

**Comment by PyvesB** [comment]
Hello @mrj 👋🏻 

Similar to #32, could you please update to the latest version of the plugin? In particular, there have been sone fixes related to js.erb files. See the changelig here: https://github.com/PyvesB/eclipse-solargraph/releases

**Comment by mrj** [comment]
Thank you for pointing out that I don't have the latest version. Looks like I'm getting 0.5 rather than 1.02 because 0.5 is the [latest](https://rubygems.org/search?query=solargraph) on _rubygems.org_. My Eclipse installed my 0.5, and continues to insist there's no updates, possibly because Marketplace is broken on my install for some reason ("No repository found at https://marketplace.eclipse.org/.").

I'll try to get Eclipse to use 1.02 and report back.

**Comment by mrj** [comment]
I see now that I had/have the latest Solargraph Gem (0.5) and latest Eclipse Plugin (1.02).

I still get the same error trying to open .js.erb files.

**Comment by PyvesB** [comment]
Okay, thanks for confirming! Does this happen with every single js.erb file, even simple ones?

**Comment by mrj** [comment]
Yes, even if the file is empty (e.g. doing new-file in Eclipse).

I tried half a dozen other .*.erb variants, and .js.erb was the only to give the error.

**Comment by PyvesB** [comment]
Thanks for the information. Something probably broke in recent Eclipse versions, will take a look in the coming days/weeks.

**Comment by PyvesB** [comment]
Please update to version 1.0.3 of the plugin, the issue with js.erb files should be fixed. 😉

**Comment by mrj** [comment]
Yes fixed. Thank you.
