### ISSUE TITLE
Initializing Language Server stuck at 28%

### ISSUE THREAD

**Issue by stormwatch** [PyvesB/eclipse-solargraph#35]
I restarted Eclipse four or five times to compare log files, If I move the cursor (I have the VIM emulation enabled) more stuff gets logged, always cycling the commands: initialize, exit, and shutdown.
[io.github.pyvesb.eclipse_solargraph.log](https://github.com/user-attachments/files/16355045/io.github.pyvesb.eclipse_solargraph.log)

The last couple of times, a pop-up error window also showed up.
![image](https://github.com/user-attachments/assets/c71e2c30-42a4-4873-9e31-9c7a4db53f58)

**Comment by PyvesB** [comment]
Hey 👋🏻 

I don't see anything fishy in the logs: Eclipse tries initialising the language server, but it doesn't respond. Does the same issue happen with an empty workspace that just has a trivial Ruby hello world file?
