### ISSUE TITLE
Plugin doesn't seem to handle paths with spaces properly.

### ISSUE THREAD

**Issue by ams-tschoening** [PyvesB/eclipse-solargraph#7]
This plugin has been [suggested](https://www.eclipse.org/forums/index.php?t=rview&th=1102129) as a replacement for DLTK, but after installing and restarting Eclipse errors like the following get logged when it tries to install itself:

    Unexpected exit value 1 from command [cmd.exe, /c, gem install -V -n C:\Users\tschoening\Documents\Eclipse\Ruby GitHub\.metadata\.plugins\io.github.pyvesb.eclipse_solargraph solargraph]
Error details:
ERROR:  Could not find a valid gem 'GitHub\.metadata\.plugins\io.github.pyvesb.eclipse_solargraph' (>= 0) in any repository

The problem most likely is that the path containing spaces is not quoted properly. The following executed manually on the shell succeeds:

    cmd.exe /c gem install -V -n "C:\Users\tschoening\Documents\Eclipse\Ruby GitHub\.metadata\.plugins\io.github.pyvesb.eclipse_solargraph" solargraph

[Source line](https://github.com/PyvesB/eclipse-solargraph/blob/master/eclipse-solargraph-plugin/src/main/java/io/github/pyvesb/eclipse_solargraph/utils/GemHelper.java#L32):

    String[] command = CommandHelper
				.getPlatformCommand("gem install -V " + "-n " + pluginStateLocation + " " + gem.toLowerCase());

**Comment by PyvesB** [comment]
Hello @ams-tschoening,

Thanks for reporting this issue! Your analysis sounds correct, adding double quotes in `GemHelper` on lines 32 and 55 would probably solve the problem.

Would you like to submit a pull request with the fix?
